### ISSUE TITLE
Viewer creation fails in python. Error "gepetto.corbaserver.gepetto.Error(msg='There is no windows with that name')"

### ISSUE THREAD

**Issue by stonneau** [humanoid-path-planner/hpp-gepetto-viewer#48]
Not sure this is the appropriate package (I never understood fully the gepetto viewer structure, sorry)

I have the latest installation of the hpp framework on ubuntu 18.04 (clean install)

The attached minimal python script generates the following error :

Thanks a lot for your [help!](https://github.com/humanoid-path-planner/hpp-gepetto-viewer/files/6286198/problem.txt)

```
/opt/openrobots/lib/python3.6/site-packages/hpp/gepetto/viewer.py in createWindowAndScene(self, viewerClient, name)
    175         try:
--> 176             self.windowId = viewerClient.gui.getWindowID (self.windowName)
    177         except GepettoError:

/opt/openrobots/lib/python3.6/site-packages/gepetto/corbaserver/graphical_interface_idl.py in getWindowID(self, *args)
    447     def getWindowID(self, *args):
--> 448         return self._obj.invoke("getWindowID", _0_gepetto.corbaserver.GraphicalInterface._d_getWindowID, args)
    449 

Error: gepetto.corbaserver.gepetto.Error(msg='There is no windows with that name')

During handling of the above exception, another exception occurred:

COMM_FAILURE                              Traceback (most recent call last)
/media/data/dev/linux/hpp/src/arumini-rbprm/test/problem.py in <module>
     18 vf = ViewerFactory (ps)
     19 
---> 20 v = Viewer (ps)

/opt/openrobots/lib/python3.6/site-packages/hpp/gepetto/viewer.py in __init__(self, problemSolver, viewerClient, ghost, collisionURDF, displayName, displayArrows, displayCoM)
    110                else:
    111                    raise e
--> 112         self.createWindowAndScene (viewerClient, "hpp_")
    113         self.client = viewerClient
    114         self.callbacks = []

/opt/openrobots/lib/python3.6/site-packages/hpp/gepetto/viewer.py in createWindowAndScene(self, viewerClient, name)
    176             self.windowId = viewerClient.gui.getWindowID (self.windowName)
    177         except GepettoError:
--> 178             self.windowId = viewerClient.gui.createWindow (self.windowName)
    179         self.sceneName = self.windowName
    180 

/opt/openrobots/lib/python3.6/site-packages/gepetto/corbaserver/graphical_interface_idl.py in createWindow(self, *args)
    443 
    444     def createWindow(self, *args):
--> 445         return self._obj.invoke("createWindow", _0_gepetto.corbaserver.GraphicalInterface._d_createWindow, args)
    446 
    447     def getWindowID(self, *args):

COMM_FAILURE: CORBA.COMM_FAILURE(omniORB.COMM_FAILURE_WaitingForReply, CORBA.COMPLETED_MAYBE)
```

**Comment by stonneau** [comment]
@nim65s sorry to push, but any idea where this comes from ? I can't really display any robot at the moment

**Comment by florent-lamiraux** [comment]
Can you replace line 20 by
```
v=vf.createViewer()
```
?

**Comment by stonneau** [comment]
Hi yes it works thanks a lot !
Is the above behaviour expected now ?  Thanks

**Comment by florent-lamiraux** [comment]
I do not know why you got the exception above, but the usual way of doing is to create an instance of `ViewerFactory` and to load obstacles with this instance. Doing so, the `ViewerFactory` instance stores the commands to send to `gepetto-gui` in order to load
the obstacle in gepetto-gui.
Method `createViewer` creates an instance of class `Viewer` which is a client to `gepetto-gui` and sends all the commands to `gepetto-gui` via this client.

Doing so enables us
  1. to synchonize the models in `hppcorbaserver` and in `gepetto-gui`,
  2. to restart `gepetto-gui` while `hppcorbaserver` is already initialized. `vf.createViewer()` resend all the commands to the new `gepetto-gui`instance to load the robots and obstacles,
  3. to restart `hppcorbaserver` while `gepetto-gui` is running: if an object is already in `gepetto-gui`, it is not reloaded.

**Comment by stonneau** [comment]
Hi,
thanks a lot. The aforementioned method has been working for at least 1 year however...
Anyway my problem is solved thanks
